server:
  port: 8080

spring:
  datasource:
    name: campusmacket  #数据库名
    url: jdbc:mysql://localhost:3306/campusmacket?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root  #账户
    password: MySQLPandawei000  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #链接驱动

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件